markdown:   kramdown

# Name of your site (displayed in the header)
name: Handwritten Computer Programs

# Short bio (displayed in the header)
description: 

# URL of your favicon image (Use .ico file format for better quality)
favicon: 

error:
  img: https://raw.githubusercontent.com/sakhsain/jekyll-vitae/main/assets/images/error-image.png # URL of an image that you want to use for the '404 - Page not found' page

mail:
  url:  # URL of your email address (e.g. person@example.com)
  address:  #Write whatever you want :-)

github:
  url:   # URL of your GitHub account (e.g. https://github.com/username)
  username: 

linkedin:  # URL of your linkedin address 
  url:  
  username: 

  
# If you're deploying your site at a repository on GitHub pages
# (http://username.github.io/repo-name)
# and not your user repository (http://username.github.io)
# then add in the baseurl here, like this: "/repo-name"
baseurl: "/HandwrittenComputerPrograms"
