markdown:   kramdown


# Site settings
title: Handwritten Computer Programs 
email: sakhawat@dpi.gov.bd
url: https://github.com/sakhsain/sakhsain.github.io
description: "A collection of handwritten program images"
keywords: "images, handwritten"
meta_author: Sakhawat Hossain 

# URL of your favicon image (Use .ico file format for better quality)
favicon: https://github.com/sakhsain/HandwrittenComputerPrograms/blob/67c07dd974a24e377ae689ca473b7182f11deac4/assets/favicon.png

